# -*- coding: utf-8 -*-

REDIS_HOST="127.0.0.1"
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD=""


MYSQL_HOST = "127.0.0.1"
MYSQL_PORT = 3306
MYSQL_AUTOCOMMIT = True
MYSQL_CHARSET = 'utf8'
MYSQL_USER = "root"
MYSQL_PASSWD = "GoBelieve123456"
MYSQL_DATABASE = "gobelieve"
MYSQL = (MYSQL_HOST, MYSQL_PORT, MYSQL_USER, MYSQL_PASSWD, MYSQL_DATABASE, MYSQL_AUTOCOMMIT, MYSQL_CHARSET)


IM_RPC_URL = "http://127.0.0.1:6666"

APPID = 7
